host: localhost:8080
info:
  contact:
    email: m.nurbasari@gmail.com
    name: Muhammad nur basari
  description: This is a Manajemen Komponen server API Documentation.
  termsOfService: http://swagger.io/terms/
  title: Manajemen Komponen API
  version: 0.0.1
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
